version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: llama3.2:3b
      CORS_ORIGINS: "*"
      OLLAMA_AUTOPULL: "false"
    depends_on:
      - ollama
    ports:
      - "8787:8787"
    restart: unless-stopped

volumes:
  ollama:
